import { Bot, Zap, Crown } from 'lucide-react';

export const PLANS = [
    {
        id: 'FREE',
        name: 'Free Plan',
        price: 0,
        metric: '25',
        unit: 'Posts',
        pricePerUnit: '0.00',
        unitLabel: 'Post',
        features: [
            '25 generated posts/month',
            '1 voice profile',
            'Basic tone analysis',
        ],
        notIncluded: [
            'Manual scheduling',
            'Auto scheduling',
            'Calendar builder',
            'Approval workflow',
            'Dual safety layer',
        ],
        icon: Bot,
        buttonText: 'Get 25 Posts',
        buttonSub: 'Start for free',
        accent: '#7c3aed',
        gradient: 'linear-gradient(135deg, #4c1d95, #7c3aed)',
        cardBg: 'linear-gradient(170deg, #18112b, #1a1030)',
        popular: false,
    },
    {
        id: 'PRO',
        name: 'Pro Plan',
        price: 10,
        metric: 'Unlimited',
        unit: 'Posts',
        pricePerUnit: '0.10',
        unitLabel: 'Post',
        features: [
            'Unlimited post generation',
            '30-day content calendar builder',
            'Manual scheduling in calendar',
            'AI Voice refinement',
            '3 voice profiles',
            'Priority support',
        ],
        notIncluded: [
            'AI auto-build full calendar',
            'Auto-schedule posts',
            'Approval workflow',
            'Dual safety layer',
        ],
        icon: Zap,
        buttonText: 'Get Pro',
        buttonSub: 'Start your growth now',
        accent: '#ec4899',
        gradient: 'linear-gradient(135deg, #7c3aed, #ec4899)',
        cardBg: 'linear-gradient(170deg, #1a0d25, #200d2a)',
        popular: true,
    },
    {
        id: 'GROWTH',
        name: 'Growth Plan',
        price: 20,
        metric: 'Full OS',
        unit: 'AI Agent',
        pricePerUnit: '0.20',
        unitLabel: 'Unit',
        features: [
            'AI auto-build full calendar',
            'Auto-schedule posts',
            'Adjustable frequency',
            'Approval workflow',
            'Dual safety layer (Tone + Compliance)',
            'CTA optimization',
            'Repurpose into comments & DMs',
            'Unlimited voice profiles',
        ],
        notIncluded: [],
        icon: Crown,
        buttonText: 'Get Growth',
        buttonSub: 'Full OS experience',
        accent: '#7c3aed',
        gradient: 'linear-gradient(135deg, #3b0764, #6d28d9)',
        cardBg: 'linear-gradient(170deg, #15092b, #1a0f30)',
        popular: false,
    },
];
